# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Lida Karimi
title: CertTESOL, Certified IELTS Trainer & TESOL/ EFL Specialist
email: karimi86lida@gmail.com
website: www.lidak.ir

# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/2019-09-15 13.44.40.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an energetic, innovative teacher that has experience in transfer the key point of the information and developing training strategies and building strong teams from a diverse group of people. While being trained by international teacher educators,
  I am currently digging deeper into teacher training programs and trying to use modern technology to make dymanic classes and updated lesson plans.<p>
  I am most skilled in: <mark>How to teach English/IELTS</mark> and <mark>How to use technology in teaching</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Teaching and IELTS some of my other interests and hobbies are:
 - Yoga
 - Meditation
 - cycling 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
